server:
  port: 8081
  servlet:
    session:
      timeout: 360000s

    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: Sweet-Nova
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sweetnova?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sweetnova
    password: sweetnova
    hikari:
      auto-commit: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:sql/dml.sql
      platform: mysql
      encoding: UTF-8